### ISSUE TITLE
Failed to submit a new card transaction

### ISSUE THREAD

**Issue by steve3535** [steve3535/rek8s#12]
![image](https://github.com/user-attachments/assets/741ea41e-3d50-46f5-83ce-0ab0c5c35a12)

**Comment by dsrouka** [comment]
Hello boss. effectivement il y a ce bug lorsqu'on lance les fontend à partir du path. D'apprès mes recherches c'est notre navigateur qui bloque le chargement des fichiers .js sous prétexte que le site est dangereux,  or ça marchais lorsqu'on avait autoriser toutes les sources dans le backend. Pour palier ce problème, j'ai conteneuriser le serveur web frontend.

**Comment by steve3535** [comment]
OK, daccord Didier: mais je ne vois aucun Dockerfile !

**Comment by dsrouka** [comment]
c'est dans le second PR

**Comment by steve3535** [comment]
* le config.js a tjrs les ports des microservices hard coded: ca ne marche donc pas lorsquon customize les ports dans .env 
* utilises un nginx au lieu dun http python
* comment arrivez vous a faire marcher l'ensemble avec le conteneur frontend ? puisquil na plus alors accès au 127.0.0.1 ??

**Comment by dsrouka** [comment]
- Comme le frontend c'est un service qui est déployé à part, le fichier config.js  doit être synchroniser manuellement avec le fichier .env du backend.
- utilisation de nginx n'avait pas posé de problème mais comme python est léger c'est pourquoi je l'avais choisi pour les tests.
- Comme nous  utilisons Docker Desktop sur Windows/Mac, il y a un mécanisme interne qui permet au conteneur d’accéder à 127.0.0.1 de l’hôte directement, même en mode bridge. Ce comportement est intégré pour simplifier les tests et le développement, mais il n’est pas disponible sur Linux par défaut. Mais toute fois  lorsqu'on mappe une image (docker run -p...)  sur le host, par défaut toutes les requêtes de l'image vers   127.0.0.1  sont redirigées vers le host directement.
- je suggère qu'on conteneurise tous les services, pourque les services se communiquent entre eux via leur noms.

**Comment by steve3535** [comment]
> * Comme le frontend c'est un service qui est déployé à part, le fichier config.js  doit être synchroniser manuellement avec le fichier .env du backend.
> 
>     * utilisation de nginx n'avait pas posé de problème mais comme python est léger c'est pourquoi je l'avais choisi pour les tests.
> 
>     * Comme nous  utilisons Docker Desktop sur Windows/Mac, il y a un mécanisme interne qui permet au conteneur d’accéder à 127.0.0.1 de l’hôte directement, même en mode bridge. Ce comportement est intégré pour simplifier les tests et le développement, mais il n’est pas disponible sur Linux par défaut. Mais toute fois  lorsqu'on mappe une image (docker run -p...)  sur le host, par défaut toutes les requêtes de l'image vers   127.0.0.1  sont redirigées vers le host directement.
> 
>     * je suggère qu'on conteneurise tous les services, pourque les services se communiquent entre eux via leur noms.

* ok, faites tjrs qqchz de portable et deployable (dans le cloud, c linux et il nya pas docker desktop)
* ok pour conteneuriser les autres services
* not ok pour une synchro manuelle, je vais travailler dessus

**Comment by dsrouka** [comment]
d'accord Monsieur. D'ici demain je ferai le push

**Comment by dsrouka** [comment]
D'accord Monsieur, pour éviter la synchro manuelle, on peut générer le fichier config.js  au moment de lancement du conteneur avec script shell.
D'ici demain je ferai le push   avec tous les services conteneuriser
