### ISSUE TITLE
dynamic config.js

### ISSUE THREAD

**Issue by steve3535** [steve3535/rek8s#17]
* recuperer de facon dynamique les ports du backend

**Comment by steve3535** [comment]
* merci de checker et dessayer cette branche (dynamic-config.js)
* jai pu rendre dynamique le config.js
* et du coup ca ne necessite plus de conteneuriser tous les autres (on va forcement le faire top ou tard, mais du coup ce nest plus un point bloquant)
* jattends vos feedback, et si c bon pour vous je merge dans main

**Comment by dsrouka** [comment]
C'est bon de mon coté Monsieur
